//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Address = new HashSet<Address>();
        }
    
        public int ID { get; set; }
        public int RegionID { get; set; }
        public int CountryID { get; set; }
        public string City1 { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual Country Country { get; set; }
        public virtual Region Region { get; set; }
    }
}
