//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Address = new HashSet<Address>();
            this.City = new HashSet<City>();
            this.Region = new HashSet<Region>();
        }
    
        public int ID { get; set; }
        public string CountryFull { get; set; }
        public string CountryShort { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<City> City { get; set; }
        public virtual ICollection<Region> Region { get; set; }
    }
}
