//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Address = new HashSet<Address>();
            this.City = new HashSet<City>();
        }
    
        public int ID { get; set; }
        public int CountryID { get; set; }
        public string Region1 { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<City> City { get; set; }
        public virtual Country Country { get; set; }
    }
}
